
name: CADIFA Monitor

on:
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          pip install requests pandas openpyxl

      - run: |
          python baixar_cadifa.py
